version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-backend:latest
    ports:
      - "3001:3001"
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres
      JWT_SECRET: secret

  # frontend:
  #   image: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-frontend:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     DATABASE_URL: postgresql://postgres:password@db:5432/postgres

volumes:
  postgres-data:
