-- AlterTable
ALTER TABLE "Room" ADD COLUMN     "creatorId" INTEGER NOT NULL DEFAULT 1;

-- AddForeignKey
ALTER TABLE "Room" ADD CONSTRAINT "Room_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
